branch-defaults:
  default:
    environment: Cns-dev-feedbk-wkr-app-env
environment-defaults:
  Cns-dev-feedbk-wkr-app-env:
    branch: null
    repository: null
global:
  application_name: cns-dev-feedbk-wkr-app
  default_ec2_keyname: aws-eb
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
