branch-defaults:
  changes:
    environment: Cns-wrkr-eb-dev-app-env
environment-defaults:
  Cns-wrkr-eb-dev-app-env:
    branch: null
    repository: null
global:
  application_name: cns-wrkr-eb-dev-app
  default_ec2_keyname: CNS-KP-Dev
  default_platform: Python 3.11 running on 64bit Amazon Linux 2023
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: git
  workspace_type: Application
